# Training Notebook

In [1]:
import sys
import os

# Add the parent directory to sys.path
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

from ml_attack import check_secret, clean_secret, get_no_mod, LWEDataset, get_filename_from_params, get_default_params, get_vector_distribution
from ml_attack.utils import get_percentage_true_b, get_expected_percentage_true_b
from ml_attack.train import LinearComplex, train_until_stall

import numpy as np
import torch
import torch.nn as nn

from sklearn.metrics import confusion_matrix, classification_report
from sklearn.linear_model import HuberRegressor

## Dataset creation

Training debug:

In [2]:
filename = "./../../data/data_n_128_k_1_s_binary_7d69d_20.pkl"

if os.path.exists(filename):
    print(f"Loading dataset from {filename}")
    dataset = LWEDataset.load_reduced(filename)
    params = dataset.params
    dataset.initialize_secret()
else:
    print(f"File {filename} does not exist.")

Loading dataset from ./../../data/data_n_128_k_1_s_binary_7d69d_20.pkl


In [3]:
in_candidates = 0
exact_candidates = 0
indeces = []

dataset.params["approximation_std"] = 2
dataset.approximate_b()

secret = dataset.get_secret()
A_reduced = dataset.get_A()
b_reduced = dataset.get_B()

b_real = get_no_mod(params, A_reduced, secret, b_reduced)

mask = np.zeros(A_reduced.shape[0], dtype=np.bool)
c = np.zeros(A_reduced.shape[0])

probs_fake = []
probs_real = []

for i in range(len(b_real)):
    true_b = b_real[i]

    candidates = dataset.b_candidates[i]
    probs = dataset.b_probs[i]
    c[i] = (true_b - dataset.best_b[i]) // params['q']

    if true_b in candidates:
        in_candidates += 1
        if true_b == dataset.best_b[i]:
            exact_candidates += 1
            mask[i] = True
            probs_real.append(np.max(probs))
        else:
            #print(f"Index {i}: {true_b} not the best candidate: {candidates[np.argmax(probs)]} with prob {np.max(probs)}")
            #print(f"Other candidates: {candidates} with probs {probs}")
            indeces.append(i)
            probs_fake.append(np.max(probs))
    else:
        #print(f"Index {i}: {true_b} not in set: {candidates}")
        indeces.append(i)
    
length = len(b_real)
print(f"True B in candidate set: {in_candidates} / {length} ({100 * in_candidates / length:.2f}%)")
print(f"True B is the best candidate: {exact_candidates} / {length} ({100 * exact_candidates / length:.2f}%)")
print(f"Indeces: {indeces}")
print(f"C values: {sorted(list(set(c.tolist())))}")
print("C value counts:")
unique_c, counts_c = np.unique(c, return_counts=True)
for val, count in zip(unique_c, counts_c):
    print(f"  C = {val}: {count}")
print(f"Mean prob of fake candidates: {np.mean(probs_fake):.4f} (std: {np.std(probs_fake):.4f})")
print(f"Mean prob of real candidates: {np.mean(probs_real):.4f} (std: {np.std(probs_real):.4f})")

True B in candidate set: 37332 / 37588 (99.32%)
True B is the best candidate: 20164 / 37588 (53.64%)
Indeces: [0, 2, 4, 6, 11, 15, 16, 17, 18, 23, 30, 31, 32, 37, 40, 44, 45, 47, 49, 51, 55, 57, 58, 60, 61, 62, 63, 64, 65, 70, 71, 73, 74, 81, 83, 88, 89, 92, 93, 94, 95, 97, 98, 99, 102, 106, 107, 110, 114, 115, 116, 121, 128, 129, 131, 132, 134, 135, 137, 140, 144, 146, 152, 155, 160, 167, 169, 172, 175, 176, 177, 180, 182, 183, 184, 186, 190, 194, 201, 203, 205, 206, 209, 211, 212, 213, 218, 221, 223, 225, 226, 228, 231, 232, 233, 234, 236, 238, 240, 243, 244, 246, 248, 249, 250, 253, 256, 261, 263, 265, 266, 268, 272, 273, 274, 276, 282, 283, 285, 289, 290, 291, 294, 295, 296, 297, 298, 305, 306, 307, 308, 311, 312, 317, 318, 319, 322, 325, 326, 327, 330, 331, 332, 333, 335, 336, 338, 342, 343, 344, 346, 347, 348, 350, 353, 355, 356, 359, 362, 363, 365, 366, 367, 368, 371, 372, 373, 374, 376, 378, 380, 383, 386, 388, 389, 390, 391, 393, 395, 396, 397, 399, 400, 403, 410, 412, 414, 41

In [4]:
percentages = [0.01, 0.05, 0.1, 0.2, 0.4, 0.6, 0.8, 1.0]
for p in percentages:
    expected = get_expected_percentage_true_b(dataset, p, verbose=True)
    actual = get_percentage_true_b(dataset, p, verbose=True)

[BEST 1% STD] Expected true B is best candidate: 62.21%
[BEST 1% STD] True B is the best candidate: 237 / 375 (63.20%)
[BEST 5% STD] Expected true B is best candidate: 60.10%
[BEST 5% STD] True B is the best candidate: 1146 / 1879 (60.99%)
[BEST 10% STD] Expected true B is best candidate: 59.08%
[BEST 10% STD] True B is the best candidate: 2207 / 3758 (58.73%)
[BEST 20% STD] Expected true B is best candidate: 58.02%
[BEST 20% STD] True B is the best candidate: 4378 / 7517 (58.24%)
[BEST 40% STD] Expected true B is best candidate: 56.67%
[BEST 40% STD] True B is the best candidate: 8469 / 15035 (56.33%)
[BEST 60% STD] Expected true B is best candidate: 55.82%
[BEST 60% STD] True B is the best candidate: 12381 / 22552 (54.90%)
[BEST 80% STD] Expected true B is best candidate: 55.10%
[BEST 80% STD] True B is the best candidate: 16329 / 30070 (54.30%)
Expected true B is best candidate: 54.35%
True B is the best candidate: 20164 / 37588 (53.64%)


In [5]:
_, _, std_B = dataset.get_b_distribution()
choosen_percentage = 0.05

num_selected = int(len(std_B) * choosen_percentage)
selected_indices = np.argsort(std_B)[:num_selected]

In [6]:
from statsmodels.robust.norms import TukeyBiweight
import statsmodels.api as sm

A_reduced = dataset.get_A()[selected_indices]
best_b = dataset.best_b[selected_indices]
c = c[selected_indices]

rlm_model = sm.RLM(best_b, A_reduced, M=TukeyBiweight(c=1))
expected_s, _, std_s = get_vector_distribution(dataset.params, dataset.params['secret_type'], dataset.params['hw'])
start_params = np.random.normal(loc=expected_s, scale=std_s, size=A_reduced.shape[1])
rlm_results = rlm_model.fit(maxiter=dataset.params['max_iter'],
                            tol=dataset.params['tol'],
                            start_params=start_params,
                            conv='coefs')
raw_guessed_secret = rlm_results.params

guessed_secret = clean_secret(raw_guessed_secret, params)
if check_secret(guessed_secret, dataset.A, dataset.B, params):
    print("Secret guessed correctly!")
else:
    print("Wrong secret guessed!")

Wrong secret guessed!


## Unsupervised Learning Outlier detection

In [7]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

loss_fn = nn.MSELoss()
model = LinearComplex(params).to(device)
model.guessed_secret = nn.Parameter(torch.tensor(raw_guessed_secret, dtype=torch.float).to(device), requires_grad=True)

A_reduced = torch.tensor(A_reduced, dtype=torch.float).to(device)
best_b = torch.tensor(best_b, dtype=torch.float).to(device)

model.eval()

grads = []
pred_b = model(A_reduced)

for i in range(len(A_reduced)):
    model.zero_grad()
    output = model(A_reduced[i].unsqueeze(0))
    loss = loss_fn(output, best_b[i].unsqueeze(0))
    loss.backward()

    grads.append(model.guessed_secret.grad.detach().cpu().numpy().copy())

grads = np.array(grads)  # shape: (N, D)
best_b = best_b.cpu().numpy()  # shape: (N,)

In [8]:
from sklearn.decomposition import PCA
import plotly.graph_objects as go

pca = PCA()
pca_transformed_data = pca.fit_transform(grads)

explained_variance = pca.explained_variance_ratio_

# plot explained variance and cumulative explained variance
fig = go.Figure()
fig.add_trace(go.Scatter(x=list(range(1, len(explained_variance) + 1)), y=np.cumsum(explained_variance), name='Cumulative explained variance'))

# Add labels on the x-axis at every 0.1 increment on the y-axis
y_values = np.arange(0.1, 1.1, 0.1)  # Adjust the range and step as needed
x_values = np.interp(y_values, np.cumsum(explained_variance), range(1, len(explained_variance) + 1))
fig.add_trace(go.Scatter(x=x_values, y=y_values, mode='text', text=[str(int(x)) for x in x_values], textposition='bottom center', name='n_components'))

fig.update_layout(title='Cumulative explained variance')
fig.show()

In [19]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Perform PCA
pca = PCA(n_components=22)
pca_transformed_data = pca.fit_transform(grads)

# Calculate the silhouette score for different numbers of clusters
silhouette_scores = []
max_clusters = 15
for n_clusters in range(2, max_clusters):
    kmeans = KMeans(n_clusters=n_clusters, random_state=0)
    clusters = kmeans.fit_predict(pca_transformed_data)
    silhouette_scores.append(silhouette_score(pca_transformed_data, clusters))

# Plot the silhouette scores
fig = go.Figure()
fig.add_trace(go.Scatter(x=list(range(2, max_clusters+1)), y=silhouette_scores, mode='lines+markers'))
fig.update_layout(title='Silhouette scores for different numbers of clusters', xaxis_title='Number of clusters', yaxis_title='Silhouette score')
fig.show()

In [25]:
from sklearn.manifold import TSNE

# Perform PCA to reduce dimensionality before t-SNE
pca = PCA(n_components=22)
pca_transformed_data = pca.fit_transform(grads)

# Perform K-means clustering
kmeans = KMeans(n_clusters=2, random_state=0)
clusters = kmeans.fit_predict(pca_transformed_data)

# Perform t-SNE
tsne = TSNE(n_components=2, perplexity=40)
tsne_transformed_data = tsne.fit_transform(pca_transformed_data)

In [ ]:
# Minimal t-SNE scatter plot by cluster
fig = go.Figure()
for cluster in np.unique(clusters):
    cluster_data = tsne_transformed_data[clusters == cluster]
    fig.add_trace(go.Scatter(
        x=cluster_data[:, 0],
        y=cluster_data[:, 1],
        mode='markers',
        marker=dict(size=3),
        showlegend=False
    ))
fig.update_layout(
    xaxis=dict(title='t-SNE Component 1', showgrid=False, showticklabels=False, linecolor='gray', linewidth=1, mirror=True),
    yaxis=dict(title='t-SNE Component 2', showgrid=False, showticklabels=False, linecolor='gray', linewidth=1, mirror=True),
    plot_bgcolor='white',
    margin=dict(l=10, r=10, t=10, b=10)
)
fig.show()
# Save the t-SNE plot with custom dimensions (e.g., width=600, height=400)
fig.write_image("tsne_clusters.pdf", width=600, height=400)

# Create a scatter plot of the t-SNE results colored by c values
import plotly.express as px

# Create a color map for unique c values, with c=0 as blue
import plotly.colors

unique_c_vals = np.unique(c)
color_map = {}
# Assign blue to c=0, and other distinct colors to other c values
base_colors = plotly.colors.qualitative.Plotly
other_colors = [col for col in base_colors if col.lower() != 'blue']
color_iter = iter(other_colors)

for val in unique_c_vals:
    if val == 0:
        color_map[val] = 'blue'
    else:
        color_map[val] = next(color_iter, 'gray')  # fallback to gray if out of colors

# Minimal t-SNE scatter plot colored by c values
fig = go.Figure()
for val in unique_c_vals:
    mask = c == val
    fig.add_trace(go.Scatter(
        x=tsne_transformed_data[mask, 0],
        y=tsne_transformed_data[mask, 1],
        mode='markers',
        marker=dict(size=3, color=color_map[val]),
        showlegend=False
    ))
fig.update_layout(
    xaxis=dict(title='t-SNE Component 1', showgrid=False, showticklabels=False, linecolor='gray', linewidth=1, mirror=True),
    yaxis=dict(title='t-SNE Component 2', showgrid=False, showticklabels=False, linecolor='gray', linewidth=1, mirror=True),
    plot_bgcolor='white',
    margin=dict(l=10, r=10, t=10, b=10)
)
fig.show()
# Save the t-SNE plot with custom dimensions (e.g., width=600, height=400)
fig.write_image("tsne_real_clusters.pdf", width=600, height=400)

In [40]:
# Minimal t-SNE scatter plot by cluster
fig = go.Figure()
for cluster in np.unique(clusters):
    if cluster == 0:
        continue
    cluster_data = tsne_transformed_data[clusters == cluster]
    fig.add_trace(go.Scatter(
      x=cluster_data[:, 0],
      y=cluster_data[:, 1],
      mode='markers',
      marker=dict(size=3, color='red'),
      showlegend=False
    ))
fig.update_layout(
    xaxis=dict(title='t-SNE Component 1', showgrid=False, showticklabels=False, linecolor='gray', linewidth=1, mirror=True),
    yaxis=dict(title='t-SNE Component 2', showgrid=False, showticklabels=False, linecolor='gray', linewidth=1, mirror=True),
    plot_bgcolor='white',
    margin=dict(l=10, r=10, t=10, b=10)
)
fig.show()
# Save the t-SNE plot with custom dimensions (e.g., width=600, height=400)
fig.write_image("tsne_clusters_outliers.pdf", width=600, height=400)

# Create a scatter plot of the t-SNE results colored by c values
import plotly.express as px

# Create a color map for unique c values, with c=0 as blue
import plotly.colors

unique_c_vals = np.unique(c)
color_map = {}
# Assign blue to c=0, and other distinct colors to other c values
base_colors = plotly.colors.qualitative.Plotly
other_colors = [col for col in base_colors if col.lower() != 'blue']
color_iter = iter(other_colors)

for val in unique_c_vals:
    if val == 0:
        color_map[val] = 'blue'
    else:
        color_map[val] = next(color_iter, 'gray')  # fallback to gray if out of colors

# Minimal t-SNE scatter plot colored by c values
fig = go.Figure()
for val in unique_c_vals:
    mask = c == val
    if val == 0:
        continue
    fig.add_trace(go.Scatter(
        x=tsne_transformed_data[mask, 0],
        y=tsne_transformed_data[mask, 1],
        mode='markers',
        marker=dict(size=3, color=color_map[val]),
        showlegend=False
    ))
fig.update_layout(
    xaxis=dict(title='t-SNE Component 1', showgrid=False, showticklabels=False, linecolor='gray', linewidth=1, mirror=True),
    yaxis=dict(title='t-SNE Component 2', showgrid=False, showticklabels=False, linecolor='gray', linewidth=1, mirror=True),
    plot_bgcolor='white',
    margin=dict(l=10, r=10, t=10, b=10)
)
fig.show()
# Save the t-SNE plot with custom dimensions (e.g., width=600, height=400)
fig.write_image("tsne_real_clusters_outliers.pdf", width=600, height=400)

In [41]:
from scipy.optimize import linear_sum_assignment
import numpy as np
import pandas as pd

# Build co-occurrence matrix (rows=c values, columns=clusters)
df = pd.DataFrame({'c': c, 'cluster': clusters})
cooccurrence = pd.crosstab(df['c'], df['cluster'])  

# Convert to cost matrix (negate frequencies for maximization)
cost_matrix = -cooccurrence.values  # Hungarian minimizes cost

# Apply Hungarian Algorithm
row_ind, col_ind = linear_sum_assignment(cost_matrix)

# Map results
c_values = cooccurrence.index.values
cluster_values = cooccurrence.columns.values

mapping = {c_values[i]: cluster_values[j] for i, j in zip(row_ind, col_ind)}
print("Optimal unique mapping from c → cluster:")
for k, v in mapping.items():
    print(f"  c = {k} → cluster = {v}")

# Create a mapping from c values to cluster labels
inverse_mapping = {v: k for k, v in mapping.items()}
# Map each predicted cluster to the corresponding c value
predicted_c = np.array([inverse_mapping.get(cl, -99) for cl in clusters])  # -99 for unmatched
valid_mask = predicted_c != -99
y_true = np.array(c)[valid_mask]
y_pred = predicted_c[valid_mask]

from sklearn.metrics import confusion_matrix, adjusted_rand_score, normalized_mutual_info_score, fowlkes_mallows_score

print("Confusion Matrix:")
print(confusion_matrix(y_true, y_pred))

print("\nAdjusted Rand Index (ARI):", adjusted_rand_score(y_true, y_pred))
print("Normalized Mutual Information (NMI):", normalized_mutual_info_score(y_true, y_pred))
print("Fowlkes-Mallows Score (FMS):", fowlkes_mallows_score(y_true, y_pred))


Optimal unique mapping from c → cluster:
  c = -1.0 → cluster = 1
  c = 0.0 → cluster = 0
Confusion Matrix:
[[   0    7    6    0    0]
 [   0   64  284    0    0]
 [   0  103 1043    0    0]
 [   0   54  308    0    0]
 [   0    4    6    0    0]]

Adjusted Rand Index (ARI): 0.05758171911127408
Normalized Mutual Information (NMI): 0.01686340662404414
Fowlkes-Mallows Score (FMS): 0.615239350925821


In [42]:
# Get indices of samples in the cluster mapped to c=0
cluster_for_c0 = mapping[0]
indices_c0 = np.where(clusters == cluster_for_c0)[0]

get_percentage_true_b(dataset, indices=indices_c0, verbose=True)

# Prepare data for retraining
A_c0 = A_reduced[indices_c0].cpu().numpy() if hasattr(A_reduced, 'cpu') else A_reduced[indices_c0]
b_c0 = best_b[indices_c0]

# Retrain HuberRegressor on the filtered data
model_c0 = HuberRegressor(fit_intercept=True, max_iter=10000, alpha=0.001, epsilon=1)
raw_guessed_secret = model_c0.fit(A_c0, b_c0).coef_

# Clean and check the new guessed secret
guessed_secret = clean_secret(raw_guessed_secret, params)
if check_secret(guessed_secret, dataset.A, dataset.B, params):
  print("Secret guessed correctly with c=0 cluster data!")
else:
  print("Wrong secret guessed with c=0 cluster data!")

True B is the best candidate: 855 / 1647 (51.91%)
Wrong secret guessed with c=0 cluster data!


In [14]:
# Check the guessed secret
guessed_secret = clean_secret(raw_guessed_secret, params)

real_secret = dataset.get_secret()

print("Raw Guessed secret:", raw_guessed_secret)
print("Guessed secret:", guessed_secret)
print("Actual secret:", real_secret)

Raw Guessed secret: [ 0.51073605  0.42550128  0.39916929  0.54094118  0.47077919  0.43533424
  0.54285888  0.49519247  0.6013926   0.46220347  0.51848073  0.47261558
  0.42495854  0.51905775  0.51088531  0.41216762  0.47559979  0.52054988
  0.41609849  0.47307815  0.48693673  0.42758986  0.49317296  0.54968472
  0.49356814  0.35667412  0.56346764  0.67805021  0.52301204  0.47316434
  0.38283942  0.60385874  0.79466501  0.42099807  0.35326271  0.47088023
  0.38228345  0.64896499  0.47709214  0.51962259  0.30698835  0.585966
  0.53498244  0.55321886  0.62603209  0.72169789  0.64185242  0.5044766
  0.25671544  0.5393133   0.68080752  0.55382447  0.31502145  0.55933841
  0.39065655  0.18310363  0.5978586   0.32131463  0.57267539  0.41500148
  0.13999245  0.56116564  0.2485554   0.83514546  0.67143127  0.90726439
  0.61715813  0.5316482   0.32174547  0.50354927  0.36146904  0.5345274
  0.75642335  0.58539688  0.74835423  0.85889138  0.65733468  0.84214407
  0.35006531  0.35755865  0.4680849

In [15]:
# Check the differences between the guessed and actual secret
diff = guessed_secret - real_secret
raw_diff = raw_guessed_secret[diff != 0]
raw_diff[raw_diff > params['q'] // 2] -= params['q']
diff_indices = np.nonzero(diff)
if len(diff[diff != 0]) > 0:
    print("Number of differences:", len(diff[diff != 0]))
    print("Difference:", raw_diff)
    print("real_secret:", real_secret[diff != 0])
    print("guessed_secret:", guessed_secret[diff != 0])
    print("Indices of differences:", diff_indices)

Number of differences: 58
Difference: [0.51073605 0.42550128 0.39916929 0.46220347 0.51088531 0.47559979
 0.41609849 0.42758986 0.49317296 0.35667412 0.56346764 0.52301204
 0.38283942 0.60385874 0.79466501 0.47088023 0.38228345 0.585966
 0.53498244 0.62603209 0.72169789 0.55382447 0.39065655 0.5978586
 0.32131463 0.56116564 0.67143127 0.5316482  0.32174547 0.50354927
 0.36146904 0.5345274  0.75642335 0.58539688 0.35006531 0.46808499
 0.36067466 0.22547669 0.68863321 0.48315151 0.49472198 0.74819814
 0.42569431 0.59280214 0.3209197  0.44838957 0.94763909 0.50253378
 0.37411324 0.38162392 0.49218235 0.70838805 0.49884856 0.55866202
 0.8507596  0.67216951 0.51871579 0.46590355]
real_secret: [0 1 1 1 0 1 1 1 1 1 0 0 1 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 1 0 1 0 0 0 1 1 1
 1 0 1 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 0 0 1]
guessed_secret: [1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 1.
 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1. 1.
 0. 0. 0. 1. 0. 1. 1. 

In [16]:
close_to_integer = np.abs(raw_guessed_secret - np.round(raw_guessed_secret))
sorted_indices = np.argsort(-close_to_integer)
print("Sorted uncertain indices:", sorted_indices)
print("Sorted uncertain values:", np.round(close_to_integer[sorted_indices], 3))

if len(diff_indices[0]) > 0:
  diff_indices_in_sorted = [np.where(sorted_indices == i)[0][0] for i in diff_indices[0]]
  print("Worst case scenario:", max(diff_indices_in_sorted))

Sorted uncertain indices: [119 107  69  47   7  96  24  22 116   0  14  20  95  10 124  13  39  17
  38  28  16  29  19  11  35   4  87  67  80 118 127  71  42  82   9  49
   3   6  23 105  84  43  51  91 121  53  61 110  26   5 100  21  58  98
   1  12  33  85  18  59  73  41  15 101  56 102   2   8  31  54  89 104
  66  30  36 113 112  44  70  81  46  79  90  25  34  37  78  76  64 123
 126  27  68  57 103  50  52  94  40 117 114  45 115  48  97  74  62  72
 109  88  92 125  86  93  32  83  55  63  77 122  75  60  99 111  65 106
 108 120]
Sorted uncertain values: [0.499 0.497 0.496 0.496 0.495 0.495 0.494 0.493 0.492 0.489 0.489 0.487
 0.483 0.482 0.481 0.481 0.48  0.479 0.477 0.477 0.476 0.473 0.473 0.473
 0.471 0.471 0.47  0.468 0.468 0.467 0.466 0.465 0.465 0.464 0.462 0.461
 0.459 0.457 0.45  0.448 0.448 0.447 0.446 0.445 0.441 0.441 0.439 0.438
 0.437 0.435 0.432 0.428 0.427 0.426 0.426 0.425 0.421 0.417 0.416 0.415
 0.415 0.414 0.412 0.407 0.402 0.401 0.399 0.399 0.396 0.391 0.

In [17]:
from itertools import product

# Find values in raw_guessed_secret that are within ±0.1 of an integer
close_to_integer = np.abs(raw_guessed_secret - np.round(raw_guessed_secret)) < 0.2
uncertain_count = np.sum(~close_to_integer)
print("Number of uncertain values:", uncertain_count)

# Calculate the number of brute force attacks to perform
brute_force_attempts = 2 ** uncertain_count
print("Number of brute force attempts required:", brute_force_attempts)

# Get the indices of uncertain values
uncertain_indices = np.where(~close_to_integer)[0]

real_uncertain_secret = real_secret[uncertain_indices]
print("Real uncertain secret:", real_uncertain_secret)

# Perform brute force attack
raw_uncertain_secret = raw_guessed_secret[uncertain_indices]
raw_uncertain_secret[raw_uncertain_secret > params['q'] // 2] -= params['q']
raw_uncertain_secret = raw_uncertain_secret[np.abs(raw_uncertain_secret) <= params['eta']]

lower_values = np.floor(raw_uncertain_secret)
upper_values = np.ceil(raw_uncertain_secret)

#values = product(*zip(lower_values, upper_values))

#for value in values:
#    print("Trying values:", value)
    # Create a copy of the guessed secret
#    brute_force_secret = copy.deepcopy(guessed_secret)
    # Update the uncertain values with the current combination
#    for idx, val in zip(uncertain_indices, value):
#        brute_force_secret[idx] = val
    # Check if the guessed secret is correct
#    if check_secret(brute_force_secret, dataset.A, dataset.B, params):
#        print("Brute force attack successful! Guessed secret:", brute_force_secret)
#        break

Number of uncertain values: 116
Number of brute force attempts required: 0
Real uncertain secret: [0 1 1 1 0 0 1 0 1 1 1 0 0 1 0 0 1 1 1 0 0 1 1 1 0 1 0 1 0 0 1 0 0 0 0 1 1
 1 0 1 0 0 0 1 0 0 1 1 0 1 1 0 0 1 1 0 1 1 0 0 0 0 1 0 1 0 1 0 0 0 1 1 1 0
 1 1 1 1 0 0 0 0 1 1 0 1 1 1 0 1 1 0 1 1 0 1 1 1 1 0 0 1 1 1 1 0 1 0 0 1 0
 0 0 1 0 1]


In [18]:
def report(real_secret, guessed_secret):
    """
    Print classification report and confusion matrix.
    """
  
    # Get unique sorted labels and compute confusion matrix
    labels = np.unique(np.concatenate((real_secret, guessed_secret)))
    cm = confusion_matrix(real_secret, guessed_secret, labels=labels)

    # Header
    header = "       |" + "".join([f"{l:>6}" for l in labels]) + " | Accuracy"
    print("Confusion Matrix:")
    print(header)
    print("-" * len(header))

    # Rows
    for i, row in enumerate(cm):
        label = f"{labels[i]:>6} |"
        values = "".join([f"{v:6}" for v in row])

        correct = row[i]
        total = row.sum()
        acc = correct / total if total > 0 else 0.0
        print(label + values + f" | {acc:4.1%}")

    # Print classification report
    print("\nClassification Report:")
    print(classification_report(real_secret, guessed_secret, zero_division=0))

report(real_secret, guessed_secret)

Confusion Matrix:
       |   0.0   1.0 | Accuracy
-------------------------------
   0.0 |    31    29 | 51.7%
   1.0 |    29    39 | 57.4%

Classification Report:
              precision    recall  f1-score   support

           0       0.52      0.52      0.52        60
           1       0.57      0.57      0.57        68

    accuracy                           0.55       128
   macro avg       0.55      0.55      0.55       128
weighted avg       0.55      0.55      0.55       128

