# Training Notebook

In [3]:
import sys
import os

# Add the parent directory to sys.path
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

from ml_attack import get_no_mod, LWEDataset, get_filename_from_params
from ml_attack.utils import get_continuous_reduction_default_params, get_default_params, get_percentage_true_b, get_train_default_params, cmod

import numpy as np

from scipy.linalg import circulant
from ml_attack.lwe import neg_circ

from ml_attack.continuous_reduction import ContinuousReduction
from concurrent.futures import ProcessPoolExecutor

from itertools import product

np.set_printoptions(linewidth=np.inf)

## Dataset creation

Training debug:

In [4]:
params = get_default_params()
params.update(get_continuous_reduction_default_params())
params.update(get_train_default_params())
params.update({
    'n': 16,
    'q': 3329,
    'k': 2,
    'eta': 2,
    'secret_type': 'cbd',
    'error_type': 'cbd',

    'num_gen': 4,
    'seed': 42,

    'num_matrices': 1,
    'reduction_max_size': -1,
    'float_type': 'd',
    'matrix_config': 'dual',
    'reduction_samples': -1,
    'reduction_resampling': False,
    'warmup_steps': 2,
    'bkz_block_sizes': "10:20:10",
    
    'penalty': 4,
    'verbose': True,

    "train_percentages": [0.1]
})

filename = get_filename_from_params(params)

reload = True
if os.path.exists(filename) and reload:
    print(f"Loading dataset from {filename}")
    dataset = LWEDataset.load_reduced(filename)
    params = dataset.params
    dataset.approximate_b()
else:
    print(f"Generating dataset and saving to {filename}")
    dataset = LWEDataset(params)
    dataset.initialize()
    dataset.attack(
        stop_strategy="tour",
        stop_after=1,
        attack_strategy="no"
    )

Generating dataset and saving to ./data_n_16_k_2_s_cbd_205b6.pkl
Samples coverage: 0.9141
Samples reuse: 1.0000
Attacking 1 matrices using 8 threads.


Initial arranged matrix:
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [-40  -4   0 ...   8 -79 -45]
 [ 28  24 -12 ...  16  33  28]
 [-28 -36  16 ...   3 -55 -21]]
(160, 160)
Control step:
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [ 16  24 -32 ... -34 -17  -4]
 [ 28  84  -4 ... -20  11 -47]
 [-48 -24 -28 ...  54 -24  41]]
(160, 160)
- Algo: flatter | Updated 160/149 (149 non zero) | Mean std_B: 240.62 | Min row norm: 4.00 | Min col norm: 4.00


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 0 and the array at index 1 has size 32

In [4]:
dataset.approximate_b()
get_percentage_true_b(dataset, verbose=True)

True B is the best candidate: 48 / 48 (100.00%)


np.float64(1.0)

In [5]:
num_gen = dataset.params['num_gen']
n = dataset.params['n']
k = dataset.params['k']
q = dataset.params['q']

In [6]:
dataset.A.shape

(16, 16)

In [7]:
dataset.A

array([[  963.,  -633.,  1239.,  1368.,  -142., -1076.,  1069.,  -760.,  -929., -1293., -1208.,  1332.,   310.,   923.,    34., -1299.],
       [  760.,   963.,  -633.,  1239.,  1368.,  -142., -1076.,  1069.,  1299.,  -929., -1293., -1208.,  1332.,   310.,   923.,    34.],
       [-1069.,   760.,   963.,  -633.,  1239.,  1368.,  -142., -1076.,   -34.,  1299.,  -929., -1293., -1208.,  1332.,   310.,   923.],
       [ 1076., -1069.,   760.,   963.,  -633.,  1239.,  1368.,  -142.,  -923.,   -34.,  1299.,  -929., -1293., -1208.,  1332.,   310.],
       [  142.,  1076., -1069.,   760.,   963.,  -633.,  1239.,  1368.,  -310.,  -923.,   -34.,  1299.,  -929., -1293., -1208.,  1332.],
       [-1368.,   142.,  1076., -1069.,   760.,   963.,  -633.,  1239., -1332.,  -310.,  -923.,   -34.,  1299.,  -929., -1293., -1208.],
       [-1239., -1368.,   142.,  1076., -1069.,   760.,   963.,  -633.,  1208., -1332.,  -310.,  -923.,   -34.,  1299.,  -929., -1293.],
       [  633., -1239., -1368.,   142.,  

In [8]:
import numpy as np
from scipy.linalg import qr

def extract_invertible_submatrix(R):
    # Ensure R is 2n x n
    rows, cols = R.shape
    
    # QR decomposition with row pivoting (on R^T to pivot rows of R)
    Q, R_qr, row_pivots = qr(R.T, pivoting=True)

    # Get the indices of the first n pivoted rows
    selected_rows = row_pivots[:cols]

    # Extract the square submatrix
    R_sub = R[selected_rows, :]

    # Check if the submatrix is invertible
    if np.linalg.matrix_rank(R_sub) == cols:
        return R_sub, selected_rows
    else:
        raise ValueError("Could not find invertible submatrix.")

In [9]:
dataset.R[0]

array([[  4.,  26.,  13.,  25.,  15.,  -6., -29.,  22.],
       [-29.,  22.,  -4., -26., -13., -25., -15.,   6.],
       [ -2., -18., -23.,   8.,  43.,   6.,  42., -37.],
       [  5., -16.,  27., -17., -31.,  10., -39.,  -4.],
       [ 43.,   6.,  42., -37.,   2.,  18.,  23.,  -8.],
       [-31.,  10., -39.,  -4.,  -5.,  16., -27.,  17.],
       [-60.,  -7., -22., -21.,  41., -23.,  15., -10.],
       [ 10., -60.,  -7., -22., -21.,  41., -23.,  15.],
       [ 25.,  15.,  -6., -29.,  22.,  -4., -26., -13.],
       [  6.,  29., -22.,   4.,  26.,  13.,  25.,  15.],
       [ 37.,  -2., -18., -23.,   8.,  43.,   6.,  42.],
       [  4.,  19.,  23.,  -4.,  51., -43.,  -4.,  15.],
       [-12.,  26., -33.,  18., -12., -25.,  13.,   6.],
       [  8.,  43.,   6.,  42., -37.,   2.,  18.,  23.],
       [  4.,   5., -16.,  27., -17., -31.,  10., -39.],
       [ 36., -22.,  20., -41.,  -5., -15.,  27., -56.],
       [ 22.,  -4., -26., -13., -25., -15.,   6.,  29.],
       [ 16.,   3., -41.,  -3.,

In [10]:
neg_circ(dataset.R[0][0]).T

array([[  4.,  26.,  13.,  25.,  15.,  -6., -29.,  22.],
       [-22.,   4.,  26.,  13.,  25.,  15.,  -6., -29.],
       [ 29., -22.,   4.,  26.,  13.,  25.,  15.,  -6.],
       [  6.,  29., -22.,   4.,  26.,  13.,  25.,  15.],
       [-15.,   6.,  29., -22.,   4.,  26.,  13.,  25.],
       [-25., -15.,   6.,  29., -22.,   4.,  26.,  13.],
       [-13., -25., -15.,   6.,  29., -22.,   4.,  26.],
       [-26., -13., -25., -15.,   6.,  29., -22.,   4.]])

In [11]:
A_to_reduce = np.stack([dataset.A[ind] for ind in dataset.indices])

In [12]:
cmod(neg_circ(dataset.R[0][0]).T @ A_to_reduce[0], q)

array([[ 269.,   73.,  -69.,  -11.,  -30.,  -94., -144.,  -77.,  -32.,  -18.,  -48.,  154.,   58., -108.,   93., -198.],
       [  77.,  269.,   73.,  -69.,  -11.,  -30.,  -94., -144.,  198.,  -32.,  -18.,  -48.,  154.,   58., -108.,   93.],
       [ 144.,   77.,  269.,   73.,  -69.,  -11.,  -30.,  -94.,  -93.,  198.,  -32.,  -18.,  -48.,  154.,   58., -108.],
       [  94.,  144.,   77.,  269.,   73.,  -69.,  -11.,  -30.,  108.,  -93.,  198.,  -32.,  -18.,  -48.,  154.,   58.],
       [  30.,   94.,  144.,   77.,  269.,   73.,  -69.,  -11.,  -58.,  108.,  -93.,  198.,  -32.,  -18.,  -48.,  154.],
       [  11.,   30.,   94.,  144.,   77.,  269.,   73.,  -69., -154.,  -58.,  108.,  -93.,  198.,  -32.,  -18.,  -48.],
       [  69.,   11.,   30.,   94.,  144.,   77.,  269.,   73.,   48., -154.,  -58.,  108.,  -93.,  198.,  -32.,  -18.],
       [ -73.,   69.,   11.,   30.,   94.,  144.,   77.,  269.,   18.,   48., -154.,  -58.,  108.,  -93.,  198.,  -32.]])

In [9]:
cmod(dataset.R[0] @ dataset.A, q)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 64 is different from 16)

## Recurrent Reduction (not working)

In [40]:
dataset.A

array([[ -927., -1280.,  1081.,   721.,  -527.,  1184.,  1196.,   429.,  -541.,  -286., -1569.,   806.,  -879., -1443.,  -810.,  -935.],
       [  935.,  -927., -1280.,  1081.,   721.,  -527.,  1184.,  1196.,   429.,  -541.,  -286., -1569.,   806.,  -879., -1443.,  -810.],
       [  810.,   935.,  -927., -1280.,  1081.,   721.,  -527.,  1184.,  1196.,   429.,  -541.,  -286., -1569.,   806.,  -879., -1443.],
       [ 1443.,   810.,   935.,  -927., -1280.,  1081.,   721.,  -527.,  1184.,  1196.,   429.,  -541.,  -286., -1569.,   806.,  -879.],
       [  879.,  1443.,   810.,   935.,  -927., -1280.,  1081.,   721.,  -527.,  1184.,  1196.,   429.,  -541.,  -286., -1569.,   806.],
       [ -806.,   879.,  1443.,   810.,   935.,  -927., -1280.,  1081.,   721.,  -527.,  1184.,  1196.,   429.,  -541.,  -286., -1569.],
       [ 1569.,  -806.,   879.,  1443.,   810.,   935.,  -927., -1280.,  1081.,   721.,  -527.,  1184.,  1196.,   429.,  -541.,  -286.],
       [  286.,  1569.,  -806.,   879.,  

In [41]:
A = dataset.A.reshape((num_gen, k*n, k*n))
A_blocks = A.reshape(num_gen, k, n, k, n).transpose(0, 1, 3, 2, 4)
# Shape: (batches, k, k, n, n)
l = 2  # provided divisor of n
A_rlwe_split = A_blocks.reshape(num_gen, k, k, l, n//l, l, n//l).transpose(0, 1, 2, 3, 5, 4, 6)
# Shape: (batches, k, k, l, l, n//l, n//l)
first_row_blocks = A_rlwe_split[:, :, :, 0, :, :, :]  # Take l matrices from the 0th row
# Shape: (batches, k, k, l, n//l, n//l)
# Reshape to combine all (num_gen, k, k, l, n//l, n//l) blocks into a single array of matrices (total_blocks, n//l, n//l)
all_blocks = first_row_blocks.reshape(-1, n // l, n // l)
all_blocks

array([[[ -927., -1280.,  1081.,   721.,  -527.,  1184.,  1196.,   429.],
        [  935.,  -927., -1280.,  1081.,   721.,  -527.,  1184.,  1196.],
        [  810.,   935.,  -927., -1280.,  1081.,   721.,  -527.,  1184.],
        [ 1443.,   810.,   935.,  -927., -1280.,  1081.,   721.,  -527.],
        [  879.,  1443.,   810.,   935.,  -927., -1280.,  1081.,   721.],
        [ -806.,   879.,  1443.,   810.,   935.,  -927., -1280.,  1081.],
        [ 1569.,  -806.,   879.,  1443.,   810.,   935.,  -927., -1280.],
        [  286.,  1569.,  -806.,   879.,  1443.,   810.,   935.,  -927.]],

       [[ -541.,  -286., -1569.,   806.,  -879., -1443.,  -810.,  -935.],
        [  429.,  -541.,  -286., -1569.,   806.,  -879., -1443.,  -810.],
        [ 1196.,   429.,  -541.,  -286., -1569.,   806.,  -879., -1443.],
        [ 1184.,  1196.,   429.,  -541.,  -286., -1569.,   806.,  -879.],
        [ -527.,  1184.,  1196.,   429.,  -541.,  -286., -1569.,   806.],
        [  721.,  -527.,  1184.,  11

In [42]:
num_matrices = all_blocks.shape[0]
print(f"Total number of matrices to reduce: {num_matrices}")
args = []
for i in range(num_matrices):
    reduction = ContinuousReduction(params)
    args.append((reduction.to_state_dict(), all_blocks[i], 1))

def continuous_reduction_worker(args):
    reduction_state, matrix_to_reduce, times = args
    reduction = ContinuousReduction.from_state_dict(reduction_state)
    R, matrix_to_reduce = reduction.reduce(matrix_to_reduce, times=times)
    return R, [reduction.to_state_dict(), matrix_to_reduce, times]

n_jobs = 4  # Adjust based on your system's capabilities
with ProcessPoolExecutor(max_workers=n_jobs) as executor:
    R_reduced = []
    for i, (R, result) in enumerate(executor.map(continuous_reduction_worker, args)):
        R_reduced.append(R)
        args[i] = result

R_reduced = np.stack(R_reduced)

Total number of matrices to reduce: 2
- Algo: flatter | Updated 16/16 | Mean std_B: 107.87- Algo: flatter | Updated 16/16 | Mean std_B: 106.32



In [44]:
all_blocks

array([[[ -927., -1280.,  1081.,   721.,  -527.,  1184.,  1196.,   429.],
        [  935.,  -927., -1280.,  1081.,   721.,  -527.,  1184.,  1196.],
        [  810.,   935.,  -927., -1280.,  1081.,   721.,  -527.,  1184.],
        [ 1443.,   810.,   935.,  -927., -1280.,  1081.,   721.,  -527.],
        [  879.,  1443.,   810.,   935.,  -927., -1280.,  1081.,   721.],
        [ -806.,   879.,  1443.,   810.,   935.,  -927., -1280.,  1081.],
        [ 1569.,  -806.,   879.,  1443.,   810.,   935.,  -927., -1280.],
        [  286.,  1569.,  -806.,   879.,  1443.,   810.,   935.,  -927.]],

       [[ -541.,  -286., -1569.,   806.,  -879., -1443.,  -810.,  -935.],
        [  429.,  -541.,  -286., -1569.,   806.,  -879., -1443.,  -810.],
        [ 1196.,   429.,  -541.,  -286., -1569.,   806.,  -879., -1443.],
        [ 1184.,  1196.,   429.,  -541.,  -286., -1569.,   806.,  -879.],
        [ -527.,  1184.,  1196.,   429.,  -541.,  -286., -1569.,   806.],
        [  721.,  -527.,  1184.,  11

In [45]:
R_reduced

array([[[ -3.,   1.,  -4.,   8.,  12.,  -5., -11.,  -9.],
        [ -6.,   5.,  -2.,  14.,   5., -10.,  -1.,   1.],
        [ -1.,  -5., -15.,  -6., -15., -14.,   5.,   7.],
        [ -1.,  -8.,   8.,  13., -16.,   3.,  17.,  -8.],
        [-19.,  -6.,   1.,   0.,   0.,   5.,  11., -21.],
        [  8.,  -5.,  -9.,  10., -14.,  -3., -17., -18.],
        [ -1., -13.,  17.,  17.,   5.,   4., -12.,   2.],
        [  1., -15.,  14.,  11.,   8.,  -2.,   7.,   5.],
        [ -8.,  12.,  -6.,   3.,  11.,  21.,   2., -14.],
        [ -6.,   0.,   4., -13.,  -9.,  -3., -25.,   5.],
        [ -3., -16.,   7.,   1.,  11.,   2.,  -1.,  -5.],
        [  1.,  -7.,  -2., -14.,  13., -17.,   8.,  -6.],
        [  0.,  11.,   6.,  20.,  -7.,  -9.,   3.,  12.],
        [  0.,  10., -12.,  -4.,  -6., -24., -11., -14.],
        [-22.,  -2.,  -5.,  20.,  -8.,  -5.,  -9.,  13.],
        [  7.,   7., -14.,   4.,   3., -14.,   8., -15.]],

       [[ 10., -13.,   1.,   5.,  -1.,  -5.,   0.,  -8.],
        [ 11

In [84]:
R_reduced= R_reduced[:, :n//2]
R_reduced[0]

array([[ -3.,   1.,  -4.,   8.,  12.,  -5., -11.,  -9.],
       [ -6.,   5.,  -2.,  14.,   5., -10.,  -1.,   1.],
       [ -1.,  -5., -15.,  -6., -15., -14.,   5.,   7.],
       [ -1.,  -8.,   8.,  13., -16.,   3.,  17.,  -8.],
       [-19.,  -6.,   1.,   0.,   0.,   5.,  11., -21.],
       [  8.,  -5.,  -9.,  10., -14.,  -3., -17., -18.],
       [ -1., -13.,  17.,  17.,   5.,   4., -12.,   2.],
       [  1., -15.,  14.,  11.,   8.,  -2.,   7.,   5.]])

In [83]:
all_blocks[0]

array([[ -927., -1280.,  1081.,   721.,  -527.,  1184.,  1196.,   429.],
       [  935.,  -927., -1280.,  1081.,   721.,  -527.,  1184.,  1196.],
       [  810.,   935.,  -927., -1280.,  1081.,   721.,  -527.,  1184.],
       [ 1443.,   810.,   935.,  -927., -1280.,  1081.,   721.,  -527.],
       [  879.,  1443.,   810.,   935.,  -927., -1280.,  1081.,   721.],
       [ -806.,   879.,  1443.,   810.,   935.,  -927., -1280.,  1081.],
       [ 1569.,  -806.,   879.,  1443.,   810.,   935.,  -927., -1280.],
       [  286.,  1569.,  -806.,   879.,  1443.,   810.,   935.,  -927.]])

In [81]:
RA = cmod(R_reduced[0] @ all_blocks[0], q)
RA

array([[107.,   3.,  97., -18., -23.,  17.,  -6., -18.],
       [ 43.,  -1., -20., -12., -35.,  40.,  -2., 124.],
       [ 35., -20., -11., -19.,  24.,  41.,  78.,  77.],
       [-43., -25.,  26., -59., -28.,  32.,  49., -52.],
       [ 62.,  55.,  50., -27.,  37., -12.,  -7., -22.],
       [-54., -22.,  -8.,   4.,   1.,  -4., -93., -23.],
       [  1., -43.,  41., -14.,  16., -52., -11., -18.],
       [ 28.,   8.,   2.,  48., -31.,  -7.,  41., -76.]])

In [98]:
def build_twisted_matrix(blocks):
    """
    Given a list of l matrices (R1', R2', ..., Rl'), construct the twisted RLWE matrix.
    """
    l = len(blocks)
    block_size = blocks[0].shape[0]
    full_size = l * block_size
    result = np.zeros((full_size, full_size))

    for i in range(l):
        for j in range(l):
            idx = (j - i) % l
            sign = (-1) ** ((j - i) > 0)
            result[i*block_size:(i+1)*block_size, j*block_size:(j+1)*block_size] = sign * blocks[idx]
    return result

In [134]:
twisted_block = cmod(build_twisted_matrix([R_reduced[0] @ all_blocks[0], R_reduced[1] @ all_blocks[1]]), q)
twisted_block @ dataset.secret

array([ 125.,  -78.,  -12.,  111.,  291.,    3., -180.,  144., -132.,  -45., -200.,  -64., -186., -176.,   19.,  -44.])

In [112]:
b = cmod(dataset.A @ dataset.secret, q)
b

array([ -715.,  1335.,  -244.,  1418.,   -48., -1432.,  -399.,  -118.,  -738.,  1203.,  -406.,  1638.,  -236.,   977.,   457., -1585.])

In [130]:
cmod(np.hstack([R_reduced[0], R_reduced[1]]) @ b, q)

array([ 657.,  305.,  705., 1604., 1344.,  769., -144.,  548.])

In [122]:
cmod(np.hstack(R_reduced) @ b, q)

array([ 657.,  305.,  705., 1604., 1344.,  769., -144.,  548.])

In [23]:
def sample_unique_indices(base, length, num_samples, seed=None):
    """
    Samples unique integers in [0, base**length) and returns base-B representations.
    """
    rng = np.random.default_rng(seed)
    total = base ** length

    if num_samples > total:
        raise ValueError("Requested more unique samples than the total possible combinations.")

    sampled = rng.choice(total, size=num_samples, replace=False)
    # Convert each to base `base` representation of length `length`
    def to_base(x):
        digits = []
        for _ in range(length):
            digits.append(x % base)
            x //= base
        return digits[::-1]  # Most significant first

    return [to_base(idx) for idx in sampled]

def sample_full_R_matrices_no_repeat(R_raw, batches, k, l, n, num_samples, seed=None):
    """
    Samples num_samples unique R matrices (shape k*n, k*n) per batch without repetition.
    """
    rng = np.random.default_rng(seed)
    num_rows = 2 * (n // l)
    block_size = n // l
    R_reshaped = R_raw.reshape((batches, k, k, l, num_rows, block_size))  # [b, k, k, l, 2n/l, n/l]

    base = num_rows ** l               # choices per (i,j)
    length = k * k                     # number of blocks per matrix
    total_combinations = base ** length

    all_batched_R = []

    for b in range(batches):
        # Precompute neg_circ matrices for all (i,j,li,row_idx)
        negcirc_dict = {}
        for i in range(k):
            for j in range(k):
                for li in range(l):
                    for r in range(num_rows):
                        vec = R_reshaped[b, i, j, li, r]
                        negcirc_dict[(i, j, li, r)] = neg_circ(vec).T

        sampled_index_vectors = sample_unique_indices(base, length, num_samples, seed + b if seed else None)

        sampled_Rs = []
        for idx_vec in sampled_index_vectors:
            full_R = np.zeros((k * n, k * n))
            for block_idx, (i, j) in enumerate(product(range(k), repeat=2)):
                flat_index = idx_vec[block_idx]

                # Decode flat_index → l row indices (base `num_rows`)
                row_choices = []
                x = flat_index
                for _ in range(l):
                    row_choices.append(x % num_rows)
                    x //= num_rows
                row_choices = row_choices[::-1]

                parts = [
                    negcirc_dict[(i, j, li, row_choices[li])]
                    for li in range(l)
                ]
                twisted_block = build_twisted_matrix(parts)
                full_R[i*n:(i+1)*n, j*n:(j+1)*n] = twisted_block

            sampled_Rs.append(full_R)

        all_batched_R.append(sampled_Rs)

    return np.stack(all_batched_R)


In [24]:
def count_total_R_matrices(n, l, k):
    """
    Calculates the total number of different full R matrices generated
    from R_raw with parameters:
    
    n: polynomial degree
    l: number of RLWE splits per LWE block
    k: module rank

    Returns: total number of (k*n, k*n) R matrices
    """
    num_rows_per_block = 2 * (n // l)
    num_combinations_per_block = num_rows_per_block ** l
    total_blocks = k * k  # each full matrix has k^2 (i,j) blocks
    total_combinations = num_combinations_per_block ** total_blocks
    return total_combinations

total_R_matrices = count_total_R_matrices(n, l, k)
print(f"Total number of different full R matrices: {total_R_matrices}")

Total number of different full R matrices: 256


In [25]:
# Generate all twisted R matrices
total_R_matrices = 1
twisted_matrices = sample_full_R_matrices_no_repeat(R_reduced, num_gen, k, l, n, total_R_matrices, seed=42)

In [26]:
twisted_matrices

array([[[[ -6.,   5.,  -2., ..., -13.,  -5., -25.],
         [ -1.,  -6.,   5., ...,   2., -13.,  -5.],
         [  1.,  -1.,  -6., ...,   1.,   2., -13.],
         ...,
         [  1.,   2., -13., ...,  -6.,   5.,  -2.],
         [  8.,   1.,   2., ...,  -1.,  -6.,   5.],
         [  2.,   8.,   1., ...,   1.,  -1.,  -6.]]],


       [[[  9.,  12.,  -3., ..., -13.,   5.,  -9.],
         [  3.,   9.,  12., ...,  10., -13.,   5.],
         [-15.,   3.,   9., ...,  10.,  10., -13.],
         ...,
         [ 10.,  10., -13., ...,   9.,  12.,  -3.],
         [ -2.,  10.,  10., ...,   3.,   9.,  12.],
         [  3.,  -2.,  10., ..., -15.,   3.,   9.]]],


       [[[ -8.,  11.,  -4., ...,  -8.,  -9.,   5.],
         [  7.,  -8.,  11., ...,   2.,  -8.,  -9.],
         [ -1.,   7.,  -8., ...,  22.,   2.,  -8.],
         ...,
         [ 22.,   2.,  -8., ...,  -8.,  11.,  -4.],
         [  9.,  22.,   2., ...,   7.,  -8.,  11.],
         [ -8.,   9.,  22., ...,  -1.,   7.,  -8.]]],


       [[[

In [27]:
import numpy as np

def multiply_sampled_Rs_by_A_vectorized(A, sampled_Rs):
    """
    A: ndarray of shape (batches, kn, kn)
    sampled_Rs: list of [batches][num_samples] with each R ∈ (kn, kn)

    Returns:
        result: ndarray of shape (batches, num_samples, kn, kn)
    """
    sampled_Rs_array = np.array(sampled_Rs)  # (batches, num_samples, kn, kn)

    # We want to do: result[b, s] = sampled_Rs[b, s] @ A[b]
    # A needs to be broadcasted to (batches, num_samples, kn, kn)
    batches, num_samples, kn, _ = sampled_Rs_array.shape
    A_expanded = A[:, None, :, :]  # (batches, 1, kn, kn)

    # Broadcasted matrix multiplication
    result = sampled_Rs_array @ A_expanded  # shape: (batches, num_samples, kn, kn)

    return result


In [28]:
RA = cmod(multiply_sampled_Rs_by_A_vectorized(A, twisted_matrices), q)

print(f"Shape of RA: {RA.shape}")  # Should be (batches * num_samples, kn, kn)

Shape of RA: (4, 1, 16, 16)


In [29]:
RA

array([[[[   62.,    75.,   -67., ...,  1018.,   823.,  1571.],
         [-1104.,   258.,  -362., ...,   846.,   847., -1190.],
         [ 1486.,  -926., -1310., ..., -1273.,  1275.,   503.],
         ...,
         [ -257.,  1442.,    58., ...,  -369., -1003.,   -37.],
         [ -115.,  1581.,   315., ..., -1045.,    73.,  1006.],
         [  869.,    54.,  1112., ...,  -499.,  -316., -1101.]]],


       [[[   15.,   -24.,    92., ...,   207.,    11.,   416.],
         [ 1277.,  -904.,  -634., ...,   343.,   481.,  -192.],
         [  299., -1662., -1316., ...,     0.,   322.,  1583.],
         ...,
         [-1595.,   140.,  1285., ...,   892.,   539.,  -406.],
         [ 1317.,   707.,   489., ..., -1298.,  -291.,  1221.],
         [ 1631.,   525., -1248., ...,   724., -1649.,  -290.]]],


       [[[    4.,     4.,    -4., ...,  -776.,  -334., -1333.],
         [-1661.,   -79., -1645., ..., -1200.,   740.,   493.],
         [ 1226.,  1144., -1476., ..., -1142.,  -136., -1053.],
    

## Enhancing RLWE (not working for MLWE)

In [24]:
dataset.R.squeeze().shape

(2, 32, 16)

In [25]:
R_reshaped = dataset.R.squeeze().reshape(num_gen, k, 2*n, k, n).transpose(0, 1, 3, 2, 4).reshape(num_gen, k * k, 2*n, n).squeeze()
R_reshaped

array([[[[ 13.,  15.,   3., ...,  -7., -11., -11.],
         [  7.,   2.,   7., ...,   4.,  -7.,   1.],
         [  2.,   7., -16., ...,  -7.,   1.,  -7.],
         ...,
         [  1.,  12.,  10., ...,  -3.,   0.,   4.],
         [ -4.,   7.,  -1., ...,   7., -16.,   9.],
         [ -3., -11., -14., ...,  -6.,  -7.,  10.]],

        [[  5.,  -3.,  -1., ...,   2.,   1.,  10.],
         [  3.,  -3.,   3., ...,  -1., -10.,  -2.],
         [ -3.,   3.,  12., ..., -10.,  -2.,  -3.],
         ...,
         [  7.,   8.,  -7., ...,  15., -11.,   0.],
         [  1.,  10.,   2., ...,   3.,  12.,  11.],
         [ -2.,   0.,  -4., ...,  -2.,   3.,   3.]],

        [[  7.,  -8.,  -1., ...,   1.,   1.,   0.],
         [  5.,  -1.,  -6., ...,  10.,   7., -17.],
         [ -2.,   5.,   2., ...,  -4.,  -3.,  15.],
         ...,
         [  8.,  -2.,   1., ...,   6.,  -4.,   8.],
         [ 14.,   9.,  21., ...,   9.,   3.,   3.],
         [ 12.,  -9.,  -2., ...,  -6.,   2.,  11.]],

        [[  0., 

In [26]:
dataset.R.squeeze().shape

(2, 32, 16)

In [9]:
RA = cmod(dataset.R.squeeze() @ dataset.A.reshape(num_gen, k*n, k*n), q)
RA

array([[[ 18., -22.,  82., ..., -31., -11.,  29.],
        [ 46.,  18., -22., ..., -52., -31., -11.],
        [-47.,   7., -22., ...,  10., -31.,  35.],
        ...,
        [-46.,  88.,  17., ...,  -4.,  87.,  23.],
        [-10., -49., -14., ...,  -1.,  78.,  -9.],
        [ 72.,  16.,  35., ...,  86., -43.,  82.]],

       [[ 22., -33.,  -3., ...,  12.,  18., -27.],
        [ 12., -16., -28., ..., -11., -31., -17.],
        [ 16.,  17.,  -8., ...,  26., -97.,   9.],
        ...,
        [-23., -62.,  68., ...,  31.,  25., -20.],
        [ 41.,  43.,   0., ...,  67.,  61.,  10.],
        [ 59., -46., -21., ...,  14.,  14.,  14.]]])

In [5]:
B = dataset.B.reshape(num_gen, -1)

In [6]:
RB = cmod(dataset.R.squeeze() @ B[..., None], q)
RB

array([[[  70.],
        [ 291.],
        [-188.],
        [ -50.],
        [-106.],
        [  42.],
        [ -36.],
        [-251.],
        [ -56.],
        [ 120.],
        [ 344.],
        [ 158.],
        [ -78.],
        [-200.],
        [ 193.],
        [  11.],
        [  83.],
        [-103.],
        [-149.],
        [  32.],
        [-178.],
        [ 189.],
        [ -73.],
        [ 118.],
        [  12.],
        [  89.],
        [ 147.],
        [-130.],
        [ -82.],
        [ 157.],
        [  57.],
        [ 262.]],

       [[  74.],
        [ 134.],
        [ -30.],
        [-161.],
        [  62.],
        [   2.],
        [ -98.],
        [ 116.],
        [-215.],
        [ 188.],
        [  -5.],
        [-105.],
        [ 204.],
        [ 158.],
        [ 138.],
        [-273.],
        [ -42.],
        [  27.],
        [-296.],
        [-233.],
        [  91.],
        [ 169.],
        [-139.],
        [  70.],
        [ -58.],
        [ -97.],
        [  1

In [10]:
RA[0, 0]

array([ 18., -22.,  82., -50.,   9.,  62.,  38., -46., 100., -15., -12.,  44., -52., -31., -11.,  29.])

In [ ]:
RA_s = dataset.R[0, 0] @ dataset.A[:, 0] % q
RA_s 

np.float64(3.0)

In [ ]:
rolled = np.roll(dataset.R[0, 0], shift=2)
rolled[0] = -rolled[0]
rolled[1] = -rolled[1]
RA_s = rolled @ dataset.A[:, 2] % q
RA_s

np.float64(3.0)

In [ ]:
R = circulant(dataset.R[0, 1])
tri = np.triu_indices(n, 1)
R[tri] *= -1
R

array([[  7.,  -1.,  12.,  -2.,  -1., -13.,  -5.,  -3.,  -5.,   9.,   9.,
         -7.,   1.,  -6.,   7.,   3.],
       [  3.,   7.,  -1.,  12.,  -2.,  -1., -13.,  -5.,   3.,  -5.,   9.,
          9.,  -7.,   1.,  -6.,   7.],
       [  7.,   3.,   7.,  -1.,  12.,  -2.,  -1., -13.,   5.,   3.,  -5.,
          9.,   9.,  -7.,   1.,  -6.],
       [ -6.,   7.,   3.,   7.,  -1.,  12.,  -2.,  -1.,  13.,   5.,   3.,
         -5.,   9.,   9.,  -7.,   1.],
       [  1.,  -6.,   7.,   3.,   7.,  -1.,  12.,  -2.,   1.,  13.,   5.,
          3.,  -5.,   9.,   9.,  -7.],
       [ -7.,   1.,  -6.,   7.,   3.,   7.,  -1.,  12.,   2.,   1.,  13.,
          5.,   3.,  -5.,   9.,   9.],
       [  9.,  -7.,   1.,  -6.,   7.,   3.,   7.,  -1., -12.,   2.,   1.,
         13.,   5.,   3.,  -5.,   9.],
       [  9.,   9.,  -7.,   1.,  -6.,   7.,   3.,   7.,   1., -12.,   2.,
          1.,  13.,   5.,   3.,  -5.],
       [ -5.,   9.,   9.,  -7.,   1.,  -6.,   7.,   3.,   7.,   1., -12.,
          2.,   1.,  1

In [ ]:
RA = R.T @ dataset.A % q
RA[RA > q // 2] -= q
RA

array([[ 1534.,   -18.,   248.,  -134.,   699.,   607.,  1578.,  -907.],
       [  913.,   303.,    99.,   523.,  -217.,   325.,  1575.,   596.],
       [   -6.,  -168.,  -859., -1476.,   755.,  1097.,   737.,  1389.],
       [ -716.,  -970., -1621.,  1655.,  -506.,   431., -1596.,   846.]])

In [ ]:
RB = R.T @ dataset.B % q
RB[RB > q // 2] -= q
RB

array([ 28.,  25., -93., -22., -59.,  90.,  65.,  39.])

In [11]:
big_R = np.stack([neg_circ(row).T for reduced_matrix in dataset.R for row in reduced_matrix])
big_R.shape

(64, 16, 16)

In [ ]:
big_RA = big_R @ dataset.A % q
big_RA[big_RA > q // 2] -= q
big_RA

array([[[  3.,   9.,  54., ..., -72.,   2., -14.],
        [ 14.,   3.,   9., ..., -54., -72.,   2.],
        [ -2.,  14.,   3., ..., -10., -54., -72.],
        ...,
        [ 10.,  54.,  72., ...,   3.,   9.,  54.],
        [-54.,  10.,  54., ...,  14.,   3.,   9.],
        [ -9., -54.,  10., ...,  -2.,  14.,   3.]],

       [[ 37., -40., -77., ...,  97.,  73.,  12.],
        [-12.,  37., -40., ...,  31.,  97.,  73.],
        [-73., -12.,  37., ...,   7.,  31.,  97.],
        ...,
        [ -7., -31., -97., ...,  37., -40., -77.],
        [ 77.,  -7., -31., ..., -12.,  37., -40.],
        [ 40.,  77.,  -7., ..., -73., -12.,  37.]],

       [[ 52., -68.,  17., ...,  -6., -22., -75.],
        [ 75.,  52., -68., ..., -30.,  -6., -22.],
        [ 22.,  75.,  52., ...,  74., -30.,  -6.],
        ...,
        [-74.,  30.,   6., ...,  52., -68.,  17.],
        [-17., -74.,  30., ...,  75.,  52., -68.],
        [ 68., -17., -74., ...,  22.,  75.,  52.]],

       ...,

       [[  2.,  40., -31

In [ ]:
np.std(big_RA, axis=-1)

array([[36.34126442, 37.15087482, 37.05654463, 36.19651226, 28.94283158,
        26.64934333, 35.35799061, 36.12132334],
       [52.84411036, 53.74476719, 55.53996309, 48.11184885, 42.66951488,
        41.14000486, 52.58980414, 55.05168027],
       [49.64561914, 48.83646179, 47.20434302, 46.63689527, 42.90978909,
        49.60846702, 50.06683034, 45.90411202],
       [55.05168027, 52.84411036, 53.74476719, 55.53996309, 48.11184885,
        42.66951488, 41.14000486, 52.58980414],
       [41.63231918, 49.61791511, 49.88925235, 48.93298989, 48.55151903,
        40.05543034, 47.08768416, 41.63231918],
       [36.12132334, 36.34126442, 37.15087482, 37.05654463, 36.19651226,
        28.94283158, 26.64934333, 35.35799061],
       [35.73776014, 36.01648928, 37.72515739, 37.61648575, 41.03885354,
        41.06930119, 32.78242669, 36.28618883],
       [59.75457618, 60.59999484, 57.59218154, 58.55753047, 58.06233181,
        60.40992779, 55.03848086, 60.1860397 ],
       [26.66429026, 26.66429026

In [ ]:
big_RB = big_R @ dataset.B % q
big_RB[big_RB > q // 2] -= q
big_RB

array([[  28.,   25.,  -93.,  -22.,  -59.,   90.,   65.,   39.],
       [ -89.,   26.,  152.,    2.,  -86., -192.,  -82.,   46.],
       [ -87., -101.,   57.,   66.,   47.,  -20.,  -63.,   -4.],
       [ -46.,  -89.,   26.,  152.,    2.,  -86., -192.,  -82.],
       [ -39.,  -69.,  -37.,  124.,  -64.,  104.,  -24.,   64.],
       [ -39.,   28.,   25.,  -93.,  -22.,  -59.,   90.,   65.],
       [-125.,   12.,  -10.,  -57.,  -21., -166.,   87.,   61.],
       [-141.,  146.,    1.,   31., -123.,  -76.,   94.,   55.],
       [   4.,  -89.,   28.,   23.,   36.,  -56.,  -89.,  -13.],
       [ -17.,   85.,   61.,  -51.,  -59.,   20.,  145.,  102.],
       [  24.,  -64.,  -39.,  -69.,  -37.,  124.,  -64.,  104.],
       [  20.,   63.,    4.,  -87., -101.,   57.,   66.,   47.],
       [ -47.,   20.,   63.,    4.,  -87., -101.,   57.,   66.],
       [  51.,   59.,  -20., -145., -102.,  -17.,   85.,   61.],
       [ -65.,    1.,  -23.,   34.,  -24.,   26.,  -32.,   64.],
       [-181.,   35.,  -3

In [ ]:
get_no_mod(big_RA, dataset.secret, big_RB, dataset.params['q'])

array([[  28.,   25.,  -93.,  -22.,  -59.,   90.,   65.,   39.],
       [ -89.,   26.,  152.,    2.,  -86., -192.,  -82.,   46.],
       [ -87., -101.,   57.,   66.,   47.,  -20.,  -63.,   -4.],
       [ -46.,  -89.,   26.,  152.,    2.,  -86., -192.,  -82.],
       [ -39.,  -69.,  -37.,  124.,  -64.,  104.,  -24.,   64.],
       [ -39.,   28.,   25.,  -93.,  -22.,  -59.,   90.,   65.],
       [-125.,   12.,  -10.,  -57.,  -21., -166.,   87.,   61.],
       [-141.,  146.,    1.,   31., -123.,  -76.,   94.,   55.],
       [   4.,  -89.,   28.,   23.,   36.,  -56.,  -89.,  -13.],
       [ -17.,   85.,   61.,  -51.,  -59.,   20.,  145.,  102.],
       [  24.,  -64.,  -39.,  -69.,  -37.,  124.,  -64.,  104.],
       [  20.,   63.,    4.,  -87., -101.,   57.,   66.,   47.],
       [ -47.,   20.,   63.,    4.,  -87., -101.,   57.,   66.],
       [  51.,   59.,  -20., -145., -102.,  -17.,   85.,   61.],
       [ -65.,    1.,  -23.,   34.,  -24.,   26.,  -32.,   64.],
       [-181.,   35.,  -3

In [ ]:
A_s = big_RA @ dataset.secret
e = (big_RB - A_s) % q
e[e > q // 2] -= q
e

array([[-12.,  14., -24.,  18., -47., -36.,   2.,  26.],
       [-24.,  -7.,  18., -17., -20., -18., -11.,  16.],
       [-29., -11.,  11.,  21., -49., -43., -25.,  18.],
       [-16., -24.,  -7.,  18., -17., -20., -18., -11.],
       [ -3.,  -1.,  -1.,  42., -15.,  15.,  13.,  -9.],
       [-26., -12.,  14., -24.,  18., -47., -36.,   2.],
       [-27.,   4.,  -7.,   0., -25., -69.,   6.,  55.],
       [ 17.,   1.,  26., -13.,  -1.,  32.,  28.,  17.],
       [ 15., -57.,  21., -14.,   8.,  -7., -60.,   6.],
       [ -9.,  42.,  36.,  -7.,   6.,  -1.,  67.,  54.],
       [-13.,   9.,  -3.,  -1.,  -1.,  42., -15.,  15.],
       [ 43.,  25., -18., -29., -11.,  11.,  21., -49.],
       [ 49.,  43.,  25., -18., -29., -11.,  11.,  21.],
       [  7.,  -6.,   1., -67., -54.,  -9.,  42.,  36.],
       [ -3.,   4., -39., -43., -58.,  32.,  -3.,  43.],
       [-22.,  -2., -30., -21.,  10.,  25., -16.,   1.]])

In [ ]:
print("RA shape:", RA.shape)
print("dataset.A shape:", dataset.A.shape)
print("dataset.R shape:", dataset.R.shape)
print("dataset.secret shape:", dataset.secret.shape)

RA shape: (8, 8)
dataset.A shape: (8, 8)
dataset.R shape: (1, 16, 8)
dataset.secret shape: (8,)
