### Min Number of matrices

In [ ]:
import sys
import os

# Add the parent directory to sys.path
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

from ml_attack.utils import calculate_min_trials, get_vector_distribution
import math 

n = 300
samples = 4
factor = 0.875
k = 1

m = int(n * factor * k)
print("n:", n)
print("m:", m)

print("Min trials:", calculate_min_trials(n=n*samples, m=m))

min_samples = int((m*k + n)) * 64 - 1
print("Min samples:", min_samples)
print("Min matrices:", min_samples // (n + m * k) + 1)

n: 300
m: 262
Min samples: 35967
Min matrices: 64


### Shortest vector length

In [7]:
import sys
import os

# Add the parent directory to sys.path
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

from ml_attack.utils import get_vector_distribution
import math 
import numpy as np
from scipy.special import erf

params = {
          'n': 512,
          'q': 3329,
          'hw': -1,
          'penalty': 4,
          'secret_type': 'cbd',
          'error_type': 'cbd',
          'eta': 2, 
          'gaussian_std': 3.0,
          'block_size': 100,
          }
_, var_secret, _ = get_vector_distribution(params, vector_type=params['secret_type'], hw=params['hw'])
_, var_error, _ = get_vector_distribution(params, vector_type=params['error_type'])
print("Variance of secret:", var_secret)
print("Variance of error:", var_error)
#w = np.ceil(np.sqrt(var_error / var_secret))
w = params['penalty']
print("Calculated w:", w)

b = params['block_size']
delta_0 = (b / (2 * np.pi * np.e) * (b * np.pi ) ** (1 / b)) ** (1/(2*(b-1)))
print(f"delta_0: {delta_0:.4f}")

m = int(np.sqrt( params['n'] * (np.log(params['q']) - np.log(w)) / np.log(delta_0)) - params['n'])
print(f"Best number of samples m: {m}")

d = m + params['n']
print(f"Total dimension d: {d}")

v = delta_0 ** d * np.exp((m * np.log(params['q']) + params['n'] * np.log(w)) / d)

p = erf(params['q'] / (2 * math.sqrt(2) * v))
print(f"Probability p: {p:.4f}")


Variance of secret: 1.0
Variance of error: 1.0
Calculated w: 4
delta_0: 1.0093
Best number of samples m: 99
Total dimension d: 611
Probability p: 0.3842


### Primal uSVP attack estimation

In [37]:
import sys
import os

# Add the parent directory to sys.path
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

from ml_attack.utils import get_vector_distribution

from estimator import *

# Define parameters
n = 256
k = 3
q = 34088624597 
hw = 6
#sigma = 3
eta = 2
sigma = get_vector_distribution({'n': n*k, 'k': 1, 'q': q, 'eta': eta}, vector_type='cbd', hw=hw)[2]

# Define the secret and error distributions
if hw > 0:
    Xs = ND.DiscreteGaussian(stddev=sigma)
else:
    Xs = ND.CenteredBinomial(eta)

#Xs = ND.SparseBinary(hw, n=n)

Xe = ND.CenteredBinomial(eta)
# Pack parameters
params = LWE.Parameters(n=n*k, q=q, Xs=Xs, Xe=Xe)
print(params)

# Estimate security
result = LWE.primal_usvp(params)
print(result)

LWEParameters(n=768, q=34088624597, Xs=D(σ=0.11), Xe=D(σ=1.00), m=+Infinity, tag=None)
         rop: ≈2^66.1
         red: ≈2^66.1
           δ: 1.008398
           β:      121
           d:     1339
         tag:     usvp


### Lattice volumes

In [ ]:
import numpy as np

def lattice_volume(B):
    gram = B.T @ B
    return np.sqrt(np.linalg.det(gram))

# Ensure m is integer for matrix dimensions
m = 4
n = 3
q = 3329
# Set penalty value (choose a reasonable integer, e.g., 1 or another value as needed)
penalty = 4

# Create random matrix A of shape (m, n) with entries in [0, q)
A = np.random.randint(0, q, size=(m, n), dtype=int)

# SALSA configuration
A_red = np.zeros((m + n, m + n), dtype=int)
A_red[n:, :m] = np.identity(m, dtype=int) * penalty
A_red[:n, m:] = np.identity(n, dtype=int) * q
A_red[n:, m:] = A

print("A reduced matrix (A_red):")
print(A_red)

# Calculate the volume of the lattice
volume = lattice_volume(A_red)
print("Volume of the lattice:", volume)

# Other configuration
A_red = np.zeros((m + n, m + n), dtype=int)
A_red[:m, :m] = np.identity(m, dtype=int) * penalty
A_red[:m, m:] = A
A_red[m:, m:] = np.identity(n, dtype=int) * q

print("A reduced matrix (A_red):")
print(A_red)

# Calculate the volume of the lattice
volume = lattice_volume(A_red)
print("Volume of the lattice:", volume)

# Other configuration
A_red = np.zeros((m + n, m + n), dtype=int)
A_red[:m, :n] = A
A_red[:m, n:] = np.identity(m, dtype=int) * penalty
A_red[m:, :n] = np.identity(n, dtype=int) * q

print("A reduced matrix (A_red):")
print(A_red)

# Calculate the volume of the lattice
volume = lattice_volume(A_red)
print("Volume of the lattice:", volume)

calc_det = q**n * penalty**m
print("Calculated determinant:", calc_det)

A reduced matrix (A_red):
[[   0    0    0    0 3329    0    0]
 [   0    0    0    0    0 3329    0]
 [   0    0    0    0    0    0 3329]
 [   4    0    0    0 1903  260 2803]
 [   0    4    0    0 3016  763 1255]
 [   0    0    4    0 2272 1920 1673]
 [   0    0    0    4 2601 1536  509]]
Volume of the lattice: 9444551753984.018
A reduced matrix (A_red):
[[   4    0    0    0 1903  260 2803]
 [   0    4    0    0 3016  763 1255]
 [   0    0    4    0 2272 1920 1673]
 [   0    0    0    4 2601 1536  509]
 [   0    0    0    0 3329    0    0]
 [   0    0    0    0    0 3329    0]
 [   0    0    0    0    0    0 3329]]
Volume of the lattice: 9444551753984.018
A reduced matrix (A_red):
[[1903  260 2803    4    0    0    0]
 [3016  763 1255    0    4    0    0]
 [2272 1920 1673    0    0    4    0]
 [2601 1536  509    0    0    0    4]
 [3329    0    0    0    0    0    0]
 [   0 3329    0    0    0    0    0]
 [   0    0 3329    0    0    0    0]]
Volume of the lattice: 9444551753983.98

### Probability of success

In [3]:
import math
from scipy.special import erf, erfinv

def min_stddev_for_success_probability(p: float, q: float) -> float:
    """
    Compute the minimum standard deviation of LWE noise (e)
    such that Pr[|e| < q/2] = p, where e ~ N(0, sigma^2).
    
    Parameters:
    - p: desired success probability (0 < p < 1)
    - q: modulus (positive number)
    
    Returns:
    - sigma: minimum standard deviation
    """
    if not (0 < p < 1):
        raise ValueError("Probability p must be between 0 and 1 (exclusive).")
    if q <= 0:
        raise ValueError("Modulus q must be positive.")

    sigma = q / (2 * math.sqrt(2) * erfinv(p))
    return sigma

# Example usage:
q = 3329
p = 0.67
sigma = min_stddev_for_success_probability(p, q)
print(f"Minimum standard deviation σ for p = {p} and q = {q} is approximately {sigma:.4f}")


Minimum standard deviation σ for p = 0.67 and q = 3329 is approximately 1708.7325


### Best number of samples m

In [7]:
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))
from ml_attack.utils import get_vector_distribution
from scipy.special import erf
import numpy as np

n = 128
k = 1
q = 3329
w = 4
b = 40


delta_0 = (b / (2 * np.pi * np.e) * (b * np.pi ) ** (1 / b)) ** (1/(2*(b-1)))
print(f"delta_0: {delta_0:.4f}")

m = int(np.sqrt(n*k * (np.log(q) - np.log(w)) / np.log(delta_0)) - n*k)
#m = int(0.875*n)
print(f"Best number of samples m: {m}")

d = m + n*k
print(f"Total dimension d: {d}")

v = delta_0 ** d * np.exp((n*k * np.log(q) + m * np.log(w)) / d)
print(f"v: {v:.4f}")

delta_0: 1.0125
Best number of samples m: 134
Total dimension d: 262
v: 2795.4863
